### ISSUE TITLE
args with custom regex doesn't seem to work

### ISSUE THREAD

**Issue by Mohitsharma44** [milin/giticket#9]
Hi, I'm probably missing something but here is what's happening:

In some of my repos, I have branch names as `XYZ-1234` or `abcd-5678_something` and at times `foobranch`. I was trying to pass `[A-Za-z]+\S?[\d?]*` to the args in `.pre-commit-config.yaml` (for `--regex`) but giticket doesn't seem to respect it.

Here is the precise `.pre-commit-config.yaml`:
```
repos:
- repo:  https://github.com/milin/giticket  
   rev: '868d9374e972f782a2950346e6b5bac869f4151f'
   - id:  giticket                                                                                                                                                                                                                           
      args: ['--regex', '[A-Za-z]+\S?[\d?]*', '--format', '[{ticket}]: {commit_msg}'] 
```

Infact, passing any regex string doesn't seem to work. Am I missing something here?

**Your operating system name and version**
MacOS Mojave 10.14.5. Running pre-commit v1.17.0 (installed using homebrew)

**Any details about your local setup that might be helpful in troubleshooting**
Any repo with different name for branches?

**Detailed steps to reproduce the bug**
Example:
```
git rev-parse --abbrev-ref HEAD
foobranch

git add bar
git commit -m "adding bar"

giticket.................................................................Passed
[foobranch b0dbf39] adding bar
1 file changed, 1 insertions(+)
create mode 100644 bar

git log -1
adding bar
```

What I was expecting:
```
git log -1
[foobranch]: adding bar
```
